#!/usr/bin/env python3
"""
shellmap - Command Mapping Engine
Compiles commands.json into Windows .bat files.

Usage:
    python generate.py           # Generate all .bat files
    python generate.py --clean   # Remove all generated files
    python generate.py --list    # Show all mappings
"""

import json
import os
import shutil
import sys
from pathlib import Path
from datetime import datetime

# === Configuration ===
CONFIG_FILE = Path(__file__).parent / "commands.json"
OUTPUT_DIR = Path(__file__).parent / "out"

# === BAT Template ===
# This template handles the prefer → fallback chain
TEMPLATE_WITH_PREFER = '''@echo off
REM ============================================
REM  {name} - generated by shellmap
REM  {description}
REM  Prefer: {prefer_list} | Fallback: {fallback}
REM  Generated: {timestamp}
REM ============================================

{prefer_checks}
REM Fallback to native command
{fallback_command}
'''

TEMPLATE_SIMPLE = '''@echo off
REM ============================================
REM  {name} - generated by shellmap
REM  {description}
REM  Maps to: {fallback}
REM  Generated: {timestamp}
REM ============================================

{fallback_command}
'''

def load_config() -> dict:
    """Load and validate commands.json"""
    if not CONFIG_FILE.exists():
        print(f"[ERROR] Config not found: {CONFIG_FILE}")
        sys.exit(1)
    
    with open(CONFIG_FILE, 'r', encoding='utf-8') as f:
        data = json.load(f)
    
    # Filter out $schema, $comment etc.
    return {k: v for k, v in data.items() if not k.startswith('$')}


def generate_prefer_checks(prefers: list, pass_args: bool = True) -> str:
    """Generate the cascading prefer checks"""
    if not prefers:
        return ""
    
    lines = []
    for tool in prefers:
        # Handle tools with built-in args (like "bat -r :10")
        tool_name = tool.split()[0]
        args_suffix = " %*" if pass_args else ""
        
        lines.append(f'''where {tool_name} >nul 2>&1
if %errorlevel%==0 (
    {tool}{args_suffix}
    exit /b %errorlevel%
)
''')
    
    return "\n".join(lines)


def generate_bat(name: str, config: dict) -> str:
    """Generate a single .bat file content"""
    description = config.get('description', f'Alias for {name}')
    prefer = config.get('prefer', [])
    fallback = config.get('fallback', config.get('windows', name))
    pass_args = config.get('passArgs', True)
    
    timestamp = datetime.now().strftime('%Y-%m-%d %H:%M')
    args_suffix = " %*" if pass_args else " %1"
    fallback_command = f"{fallback}{args_suffix}"
    
    if prefer:
        return TEMPLATE_WITH_PREFER.format(
            name=name,
            description=description,
            prefer_list=" → ".join(prefer),
            fallback=fallback,
            timestamp=timestamp,
            prefer_checks=generate_prefer_checks(prefer, pass_args),
            fallback_command=fallback_command
        )
    else:
        return TEMPLATE_SIMPLE.format(
            name=name,
            description=description,
            fallback=fallback,
            timestamp=timestamp,
            fallback_command=fallback_command
        )


def generate_all():
    """Main generation routine"""
    config = load_config()

    # Ensure output directory exists
    OUTPUT_DIR.mkdir(exist_ok=True)

    print(f"[*] cmdx - Generating {len(config)} commands...")
    print(f"    Source: {CONFIG_FILE}")
    print(f"    Output: {OUTPUT_DIR}/")
    print()

    for name, cmd_config in config.items():
        bat_content = generate_bat(name, cmd_config)
        bat_path = OUTPUT_DIR / f"{name}.bat"

        with open(bat_path, 'w', encoding='utf-8') as f:
            f.write(bat_content)

        prefer = cmd_config.get('prefer', [])
        fallback = cmd_config.get('fallback', cmd_config.get('windows', ''))

        prefer_str = f" -> {' -> '.join(prefer)} ->" if prefer else ""
        print(f"    + {name}.bat{prefer_str} {fallback}")

    print()
    print(f"[OK] Done! Add this to your PATH:")
    print(f"     {OUTPUT_DIR.absolute()}")


def clean():
    """Remove all generated files"""
    if OUTPUT_DIR.exists():
        shutil.rmtree(OUTPUT_DIR)
        print(f"[OK] Cleaned: {OUTPUT_DIR}")
    else:
        print("Nothing to clean.")


def list_mappings():
    """Display all mappings in a nice format"""
    config = load_config()

    print("[*] cmdx - Command Mappings")
    print("=" * 50)
    
    for name, cmd_config in config.items():
        prefer = cmd_config.get('prefer', [])
        fallback = cmd_config.get('fallback', cmd_config.get('windows', ''))
        desc = cmd_config.get('description', '')
        
        chain = " → ".join(prefer + [fallback]) if prefer else fallback
        print(f"  {name:10} → {chain}")
        if desc:
            print(f"  {'':10}   └─ {desc}")
    
    print("=" * 50)
    print(f"Total: {len(config)} commands")


def main():
    if len(sys.argv) > 1:
        arg = sys.argv[1]
        if arg == '--clean':
            clean()
        elif arg == '--list':
            list_mappings()
        elif arg == '--help':
            print(__doc__)
        else:
            print(f"Unknown argument: {arg}")
            print("Use --help for usage.")
    else:
        generate_all()


if __name__ == "__main__":
    main()
